Vue.createApp({
    data(){
        return{
            flowData:[
                {
                    picSrc:"images/news/news-1.png",
                    title:'美味多重享受！經典貝果組合',
                    text:'本店驕傲推出貝果組合！原味、藍莓和蜜香紅茶三種口味搭配的經典組合...',
                    tag:'優惠',
                    time:'2023.10.25'
                },
                {
                    picSrc:'images/news/news-2.png',
                    title:'日光小麥所休息公告',
                    text:'親愛的顧客，感謝您一直以來對我們的支持。日光小麥所將於10/16-10/22休...',
                    tag:'公告',
                    time:'2023.10.13'
                },
                {
                    picSrc:'images/news/news-3.png',
                    title:'品嘗地中海風味-青醬佛卡夏',
                    text:'迎接清新的風味饗宴——青醬佛卡夏！酥脆外皮包裹著濃郁的新鮮青醬，帶...',
                    tag:'New',
                    time:'2023.10.05'
                },
                {
                    picSrc:'images/news/news-2.png',
                    title:'連假物流配送調整通知',
                    text:'親愛的顧客，感謝您一直以來對我們的支持。在中秋和雙十國慶期間，由於...',
                    tag:'公告',
                    time:'2023.09.25'
                },
                {
                    picSrc:'images/news/news-4.png',
                    title:'新品上市可可豆鮮奶手拿棒',
                    text:'品味香醇，體驗獨特風味的可可豆鮮奶手拿棒！，酥脆的外皮包裹著濃郁的...',
                    tag:'New',
                    time:'2023.09.18'
                },
                {
                    picSrc:'images/news/news-2.png',
                    title:'日光小麥所參加市集公告',
                    text:'本店興奮地宣布，日光小麥所將參加9/9-9/10的八德文創市集！期間將展...',
                    tag:'公告',
                    time:'2023.09.01'
                },
                
            ]
        }
    }
}).mount('#app')